print ("Dibuat Oleh:Rayhan Syahrur Ramadhan/222410102086")
print ("PROGRAM PERHITUNGAN BODY MASS INDEX")
print("------------------------------------")
nama = input("Masukkan Nama Anda : ")
berat = float(input("Masukkan Berat Badan Anda dalam kg : "))
tinggi = float(input("Masukkan Tinggi Badan Anda dalam m : "))

BMI = berat / (tinggi**2)

if BMI < 18.5 :
    print("------------------------------------")
    print("Hasil Perhitungan")
    print("Nama         :", nama)
    print("Berat Badan  :", berat)
    print("Tinggi Badan :", tinggi)
    print("BMI          :", BMI)
    print("Keterangan   : Underweight")
elif 18.5 <= BMI < 25.0 :
    print("------------------------------------")
    print("Hasil Perhitungan")
    print("Nama         :", nama)
    print("Berat Badan  :", berat)
    print("Tinggi Badan :", tinggi)
    print("BMI          :", BMI)
    print("Keterangan   : Normal Weight")
elif 25.0 <= BMI < 30.0 :
    print("------------------------------------")
    print("Hasil Perhitungan")
    print("Nama         :", nama)
    print("Berat Badan  :", berat)
    print("Tinggi Badan :", tinggi)
    print("BMI          :", BMI)
    print("Keterangan   : Over Weight")
elif 30.0 <= BMI < 35.0 :
    print("------------------------------------")
    print("Hasil Perhitungan")
    print("Nama         :", nama)
    print("Berat Badan  :", berat)
    print("Tigggi Badan :", tinggi)
    print("BMI          :", BMI)
    print("Keterangan   : Obesity Class 1")
elif 35.0 <= BMI < 40.0 :
    print("------------------------------------")
    print("Hasil Perhitungan")
    print("Nama         :", nama)
    print("Berat Badan  :", berat)
    print("Tinggi Badan :", tinggi)
    print("BMI          :", BMI)
    print("Keterangan   : Obesity Class 2")
elif BMI >= 40.0 :
    print("------------------------------------")
    print("Hasil Perhitungan")
    print("Nama         :", nama)
    print("Berat Badan  :", berat)
    print("Tinggi Badan :", tinggi)
    print("BMI          :", BMI)
    print("Keterangan   : Obesity Class 3")
